package com.myspace.aeye;

import java.time.LocalDate;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Patient_Info implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PATIENT_INFO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PATIENT_INFO_ID_SEQ", name = "PATIENT_INFO_ID_GENERATOR")
	private String id;

	private java.lang.String name;

	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<java.lang.String> gender;

	private LocalDate birthDate;

	private java.lang.String residence;

	private java.math.BigInteger contact;

	public Patient_Info() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.List<java.lang.String> getGender() {
		return this.gender;
	}

	public void setGender(java.util.List<java.lang.String> gender) {
		this.gender = gender;
	}

	public java.lang.String getResidence() {
		return this.residence;
	}

	public void setResidence(java.lang.String residence) {
		this.residence = residence;
	}

	public java.math.BigInteger getContact() {
		return this.contact;
	}

	public void setContact(java.math.BigInteger contact) {
		this.contact = contact;
	}

	public java.time.LocalDate getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(java.time.LocalDate birthDate) {
		this.birthDate = birthDate;
	}

	public Patient_Info(java.lang.String id, java.lang.String name,
			java.util.List<java.lang.String> gender,
			java.time.LocalDate birthDate, java.lang.String residence,
			java.math.BigInteger contact) {
		this.id = id;
		this.name = name;
		this.gender = gender;
		this.birthDate = birthDate;
		this.residence = residence;
		this.contact = contact;
	}

}